from flask import Flask, jsonify, request
from flask_cors import CORS
import torch
import re
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from collections import OrderedDict

app = Flask(__name__)
CORS(app)

# Load model only ONCE
print("Loading GPT-2 model...")

model_id = "gpt2"

model = GPT2LMHeadModel.from_pretrained(model_id)
tokenizer = GPT2TokenizerFast.from_pretrained(model_id)

model.eval()

print("Model loaded successfully!")


class GPT2PPL:
    def __init__(self):
        self.model = model
        self.tokenizer = tokenizer
        self.max_length = self.model.config.n_positions
        self.stride = 512

    def getResults(self, threshold):

        if threshold < 60:
            label = 0
            return "The Text is generated by AI.", label

        elif threshold < 80:
            label = 0
            return (
                "The Text most probably contains parts generated by AI.",
                label
            )

        else:
            label = 1
            return "The Text is written by a Human.", label

    def __call__(self, sentence):

        results = OrderedDict()

        total_valid_char = re.findall("[a-zA-Z0-9]+", sentence)
        total_valid_char = sum([len(x) for x in total_valid_char])

        if total_valid_char < 100:
            return {
                "status": "Please input more text (minimum 100 characters)"
            }, "Please input more text (minimum 100 characters)"

        # Split into lines/sentences
        lines = re.split(r'(?<=[.!?])\s+', sentence)

        lines = list(
            filter(
                lambda x: (x is not None) and (len(x.strip()) > 0),
                lines
            )
        )

        # Full text perplexity
        ppl = self.getPPL(sentence)

        results["Perplexity"] = ppl

        # Per-line perplexity
        perplexity_per_line = []

        for line in lines:

            if re.search("[a-zA-Z0-9]+", line) is None:
                continue

            try:
                ppl = self.getPPL(line)
                perplexity_per_line.append(ppl)

            except Exception as e:
                print("Line Error:", e)

        # Prevent division by zero
        if len(perplexity_per_line) == 0:
            results["Perplexity per line"] = 0
            results["Burstiness"] = 0

        else:
            results["Perplexity per line"] = (
                sum(perplexity_per_line) / len(perplexity_per_line)
            )

            results["Burstiness"] = max(perplexity_per_line)

        out, label = self.getResults(
            results["Perplexity per line"]
        )

        results["label"] = label

        return results, out

    def getPPL(self, sentence):

        encodings = self.tokenizer(
            sentence,
            return_tensors="pt"
        )

        input_ids = encodings.input_ids
        attention_mask = encodings.attention_mask

        seq_len = input_ids.size(1)

        nlls = []

        prev_end_loc = 0

        for begin_loc in range(0, seq_len, self.stride):

            end_loc = min(
                begin_loc + self.max_length,
                seq_len
            )

            trg_len = end_loc - prev_end_loc

            input_ids_slice = input_ids[:, begin_loc:end_loc]

            attention_mask_slice = attention_mask[:, begin_loc:end_loc]

            target_ids = input_ids_slice.clone()

            target_ids[:, :-trg_len] = -100

            with torch.no_grad():

                outputs = self.model(
                    input_ids_slice,
                    attention_mask=attention_mask_slice,
                    labels=target_ids
                )

                neg_log_likelihood = outputs.loss * trg_len

            nlls.append(neg_log_likelihood)

            prev_end_loc = end_loc

            if end_loc == seq_len:
                break

        ppl = torch.exp(
            torch.stack(nlls).sum() / end_loc
        )

        return round(ppl.item(), 2)


gpt2ppl = GPT2PPL()


@app.route('/', methods=['POST'])
def postData():

    try:

        data = request.get_json()

        if not data:
            return jsonify({
                'error': 'No JSON data received'
            }), 400

        text = data.get('text')

        if not text:
            return jsonify({
                'error': 'No text provided'
            }), 400

        results, output = gpt2ppl(text)

        return jsonify({
            "output": output,
            "results": dict(results)
        })

    except Exception as e:

        print("SERVER ERROR:", str(e))

        return jsonify({
            'error': str(e)
        }), 500


@app.route('/', methods=['GET'])
def home():
    return jsonify({
        "message": "AI Detection Backend Running"
    })


if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=5000,
        debug=True
    )